# config_detector.py

import os
from pathlib import Path
from typing import Dict, List, Optional, Union # Import necessary types for Dict, List, Optional

# --- Project Paths ---
PROJECT_ROOT = Path(__file__).resolve().parent.parent
BASE_RESULTS_DIR = PROJECT_ROOT / "results" # General results base

# New: Dedicated directory for edge detection results
EDGE_DETECTION_RESULTS_BASE_DIR = BASE_RESULTS_DIR / "edge_detection_results"

# Important: This path is where the reconstructor saves its .pkl files
# The detector needs to know where to LOAD the reconstruction data from.
RECONSTRUCTION_RESULTS_BASE_DIR_FOR_LOADING = BASE_RESULTS_DIR / "image_reconstruction_results"


# Ensure necessary directories exist
os.makedirs(EDGE_DETECTION_RESULTS_BASE_DIR, exist_ok=True)
# The RECONSTRUCTION_RESULTS_BASE_DIR_FOR_LOADING is assumed to be created by the reconstructor


# --- Edge Detection Parameters ---
# Strategy for combining the different raw error maps ('error_original', 'error_smoothed', etc.)
# Options: 'max', 'weighted_sum', or any of the raw error map keys directly (e.g., 'error_original', 'diff_original_poly_smoothed')
ERROR_COMBINATION_STRATEGY: str = 'weighted_sum'

# Weights for 'weighted_sum' strategy (keys must match raw error map keys)
# Only used if ERROR_COMBINATION_STRATEGY is 'weighted_sum'
ERROR_COMBINATION_WEIGHTS: Dict[str, float] = {
    'error_original': 0.05,
    'error_smoothed': 0.15,
    'diff_original_poly_smoothed': 0.7,
    'diff_smoothed_poly_original': 0.1,
}
# Note: Weights will be normalized to sum to 1.0 if they don't.

# Type of thresholding to apply to the combined error map
# 'fixed': Use a fixed threshold (0.0 to 1.0)
# 'otsu': Use Otsu's method (requires scikit-image)
EDGE_THRESHOLD_TYPE: str = 'fixed' # Changed to 'fixed' as requested

# Default fixed edge threshold. This will be overridden per image in the run script.
FIXED_EDGE_THRESHOLD: float = 0.05 # A sensible default, to be specified per image later.

# Saving flags for edge detection results
SAVE_RAW_ERROR_MAPS: bool = True # Ensure all raw error maps are available for comparison
SAVE_COMPOSITE_ERROR_MAP: bool = False # Save the reassembled composite error map (set to False as we're using combined plot)
SAVE_BINARY_EDGE_MAPS: bool = True # Save the final reassembled binary edge map

# Colormap for edge error heatmaps (distinguished from general error heatmap)
EDGE_ERROR_HEATMAP_COLORMAP: str = 'plasma'


# --- Edge Strategy Comparison Plot ---
SAVE_EDGE_STRATEGY_COMPARISON_PLOT: bool = True # Whether to generate and save a comparison plot of different edge strategies

# List of strategies to compare in the comparison plot.
# Each item should be a valid ERROR_COMBINATION_STRATEGY or a raw error map key.
EDGE_STRATEGIES_TO_COMPARE: List[str] = [
    'error_original',
    'error_smoothed',
    'diff_original_poly_smoothed',
    'diff_smoothed_poly_original',
    'max',
    'weighted_sum',
]

# --- Global Matplotlib Plotting Parameters for High Quality Output ---
# These settings will be applied to all plots generated by the detector.
MATPLOTLIB_PARAMS: Dict[str, Union[str, int, float, bool, List[str]]] = {
    # Use LaTeX for text rendering (requires LaTeX distribution like TeX Live/MiKTeX)
    # Uncomment if you have LaTeX installed and want LaTeX fonts in plots
    # "text.usetex": True,
    # "font.family": "serif",
    # "font.serif": ["Computer Modern Roman"], # Or "Times New Roman" etc.

    # Default font settings if LaTeX is not used for text rendering
    "font.family": "serif",
    "font.serif": ["DejaVu Serif"], # A good default serif font

    "font.size": 12, # Base font size for plots
    "axes.labelsize": 14, # Font size for axis labels
    "legend.fontsize": 12, # Font size for legend text
    "xtick.labelsize": 12, # Font size for x-axis tick labels
    "ytick.labelsize": 12, # Font size for y-axis tick labels
    "figure.titlesize": 16, # Font size for figure titles
    "axes.titlesize": 14, # Font size for subplot titles (adjusted for edge strategy comparison)

    # Line widths and marker sizes
    "lines.linewidth": 1.5,
    "lines.markersize": 6,

    # Figure and subplot settings
    "figure.autolayout": True, # Automatically adjust subplot params for tight layout
    "savefig.dpi": 600, # DPI for raster images (PNG) - high quality for print
    "savefig.format": "pdf", # Default format for saving figures (vector graphics recommended)
    "figure.figsize": (8, 6), # Default figure size (width, height) in inches for single plots

    # Grid settings
    "axes.grid": True,
    "grid.linestyle": ':',
    "grid.alpha": 0.6,
}

# Specific DPI for raster images (PNG) when saving
PLOT_DPI = 600

# Figure size in inches for standard single plots (width, height)
PLOT_FIGURE_WIDTH_INCHES = 8.0 # Adjusted for potentially wider plots
PLOT_FIGURE_HEIGHT_INCHES = 6.0 # Adjusted for potentially taller plots
