# config_reconstructor.py

import os
from pathlib import Path
import multiprocessing
from typing import Dict, List, Optional, Union # Import necessary types for Dict, List, Optional

# --- Project Paths ---
# Assuming this config file is in a 'config' subfolder within the project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent

IMAGE_DIR = PROJECT_ROOT / "images"
BASE_RESULTS_DIR = PROJECT_ROOT / "results"

# New: Dedicated directory for image reconstruction results
RECONSTRUCTION_RESULTS_BASE_DIR = BASE_RESULTS_DIR / "image_reconstruction_results"


# Ensure necessary directories exist
os.makedirs(IMAGE_DIR, exist_ok=True)
os.makedirs(BASE_RESULTS_DIR, exist_ok=True)
os.makedirs(RECONSTRUCTION_RESULTS_BASE_DIR, exist_ok=True)


# --- Image Configuration ---
IMAGE_NAME = "Shepp_Logan_phantom" # Base name of the image (e.g., "spiral.png")
IMAGE_FILENAME = f"{IMAGE_NAME}.png"
IMAGE_PATH = IMAGE_DIR / IMAGE_FILENAME


# --- Polynomial Approximation Parameters ---
# These parameters are applied per segment
POLY_DEGREE = 5 # Degree of the polynomial approximation
NODES_METHOD = 'full_mesh' # Method for selecting interpolation/approximation nodes: 'full_mesh', 'leja', 'fekete', 'padua'
ADMISSIBLE_MESH_TYPE = 'cheb' # Type of admissible mesh to generate: 'cheb' (only supported now)
M_CHEB = 2 # Parameter 'm' for Chebyshev mesh construction (m > 1)
POLY_BASIS_USED = 1 # Polynomial basis used for approximation (1: Shifted Monomials, 2: Monomial, 3: Chebyshev) - Changed to 2 for Monomial


# --- Adaptive Segmentation Control Parameters ---
ERROR_MEASURE_TYPE = 'rmse' # Error measure for adaptive criterion: 'mse', 'mae', 'rmse'
ERROR_THRESHOLD = 0.0001 # Threshold for the error measure M(S)
MAX_DEPTH = 15 # Maximum recursive segmentation depth (0 is the whole image)
MIN_SEGMENT_SIZE = 5 # Minimum dimension (width or height) of a segment to stop subdivision


# --- Parallel Processing Parameters ---
# Set to None or 1 to disable parallel processing
# Set to an integer > 1 for a fixed number of processes
# Set to 0 to use the number of CPU cores
NUM_PROCESSES = multiprocessing.cpu_count() # Use all available CPU cores


# --- Higher Resolution Output ---
# Factor by which to upscale the reconstructed image (e.g., 2 for 2x resolution)
# Set to 1 for original resolution
UPSCALE_FACTOR = 3


# --- Results Saving and Visualization (Reconstruction specific) ---
SAVE_SEGMENT_DATA = True # Whether to save the segment data and coefficients (.pkl file)
SAVE_RECONSTRUCTED_IMAGE = True # Whether to save the reassembled approximation image
SAVE_ERROR_MAP_VIZ = True # Whether to save the normalized actual reconstruction error map visualization
SAVE_MAIN_PLOT = True # Whether to save the main plot (Original, Reconstructed, Error, Segmentation)
SAVE_SEGMENT_ERROR_HEATMAP_PLOT = True # Whether to save the segment error heatmap plot

# Additional visualization flags for reconstruction
SAVE_ERROR_DISTRIBUTION_PLOT = True # Plot histogram of final segment errors
SAVE_DEPTH_SEGMENT_COUNT_PLOT = True # Plot number of segments per depth level
SAVE_SEGMENT_SIZE_DISTRIBUTION_PLOT = True # Plot histogram of final segment sizes


# Colormaps for visualization
ERROR_HEATMAP_COLORMAP = 'viridis' # Colormap for the actual reconstruction error heatmap
SEGMENT_ERROR_COLORMAP = 'hot' # Colormap for the segment error heatmap


# --- Global Matplotlib Plotting Parameters for High Quality Output ---
# These settings will be applied to all plots generated by the reconstructor.
MATPLOTLIB_PARAMS: Dict[str, Union[str, int, float, bool, List[str]]] = {
    # Use LaTeX for text rendering (requires LaTeX distribution like TeX Live/MiKTeX)
    # Uncomment if you have LaTeX installed and want LaTeX fonts in plots
    # "text.usetex": True,
    # "font.family": "serif",
    # "font.serif": ["Computer Modern Roman"], # Or "Times New Roman" etc.

    # Default font settings if LaTeX is not used for text rendering
    "font.family": "serif",
    "font.serif": ["DejaVu Serif"], # A good default serif font

    "font.size": 12, # Base font size for plots
    "axes.labelsize": 14, # Font size for axis labels
    "legend.fontsize": 12, # Font size for legend text
    "xtick.labelsize": 12, # Font size for x-axis tick labels
    "ytick.labelsize": 12, # Font size for y-axis tick labels
    "figure.titlesize": 16, # Font size for figure titles
    "axes.titlesize": 14, # Font size for subplot titles (for reconstruction plots)

    # Line widths and marker sizes
    "lines.linewidth": 1.5,
    "lines.markersize": 6,

    # Figure and subplot settings
    "figure.autolayout": True, # Automatically adjust subplot params for tight layout
    "savefig.dpi": 600, # DPI for raster images (PNG) - high quality for print
    "savefig.format": "pdf", # Default format for saving figures (vector graphics recommended)
    "figure.figsize": (8, 6), # Default figure size (width, height) in inches for single plots

    # Grid settings
    "axes.grid": True,
    "grid.linestyle": ':',
    "grid.alpha": 0.6,
}

# Specific DPI for raster images (PNG) when saving
PLOT_DPI = 600

# Figure size in inches for standard single plots (width, height)
PLOT_FIGURE_WIDTH_INCHES = 8.0 # Adjusted for potentially wider plots
PLOT_FIGURE_HEIGHT_INCHES = 6.0 # Adjusted for potentially taller plots

# --- Other Parameters ---
# Add any other global parameters here
